version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      PORT: 9000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: admin 
      MYSQL_PASSWORD: admin1234
      MYSQL_DB: mysql-db
    ports:
      - "9000:9000"
    depends_on:
      - mysql

volumes:
  mysql_data:
